# Utiliza una imagen base de Node.js
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

RUN npm install -g pnpm

# Instala las dependencias del proyecto
RUN pnpm install

# Copia el resto de los archivos de la aplicación al directorio de trabajo
COPY . .

# Compila la aplicación
RUN pnpm run build

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 4321

# Comando para iniciar la aplicación cuando se ejecute el contenedor
CMD [ "pnpm", "start" ]