version: '3'

services:
  backend:
    image: backend,
    
    

  frontend:
    image: frontend-image
    # Configuración del frontend...

  mongodb:
    image: mongo
    # Configuración de MongoDB...

  postgres:
    image: postgres
    # Configuración de PostgreSQL...

networks:
  messaging-network:
    driver: bridge