services:
  backend:
    build: './backend'
    depends_on:
      - mongodb
      - postgres
    ports: 
      - "3000:3000"
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    env_file: './backend/.env'
    networks:
      - database
      - backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev
    depends_on:
      - backend
    ports:
      - "4321:4321"
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    networks:
      - backend
    # Configuración del frontend...

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=messaging
    ports:
      - "27017:27017"
    networks:
      - database

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: messaging
    networks:
      - database
    # Configuración de PostgreSQL...

networks:
  database:
    driver: bridge
  backend:
    driver: bridge